name: smart_bin_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project for smart bin application.
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter: 
    sdk: flutter

  percent_indicator: ^3.4.0
  dio: ^4.0.4

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/hampas_logo.png
